# Nombre del flujo de trabajo que aparecerá en la pestaña "Actions"
name: Actualizar Datos de Criptos Diariamente

# Define cuándo se debe ejecutar este flujo de trabajo
on:
  schedule:
    # Se ejecuta todos los días a las 05:00 UTC (puedes ajustar la hora).
    - cron: '0 5 * * *'
  workflow_dispatch:
    # Permite ejecutar el script manualmente desde la pestaña Actions.

# Define los trabajos que se realizarán
jobs:
  actualizar-csv:
    runs-on: ubuntu-latest

    # --- LA SOLUCIÓN ESTÁ AQUÍ ---
    # Añade este bloque para dar permisos de escritura al bot de la Action.
    # Sin esto, el comando 'git push' fallará con un error 403 (Permiso Denegado).
    permissions:
      contents: write
    # ------------------------------------------------------------------

    steps:
      # Paso 1: Descarga el código de tu repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # Paso 2: Configura el entorno de Python
      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Paso 3: Instala las librerías necesarias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      # Paso 4: Ejecuta tu script de Python
      - name: Ejecutar script para actualizar los datos
        run: python actualizar_datos.py

      # Paso 5: Guarda los cambios del archivo CSV en el repositorio
      # Este paso está muy bien hecho. Solo le faltaban los permisos generales.
      - name: Commit y Push de los cambios
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add historico_criptos.csv
          # La siguiente línea es muy inteligente: solo hace commit si de verdad hay cambios.
          git diff --staged --quiet || git commit -m "Actualización diaria de datos de criptomonedas"
          git push
